### ISSUE TITLE
Checklist Design

### ISSUE THREAD

**Issue by andrechalom** [merepresenta/merepresenta#18]
Issue para marcar as tarefas iniciais de design

- [x] Inserir cores, logo, elementos comuns no css
- [ ] Inserir fontes
- [x] Inserir imagens de fundo
- [x] Reformular menus e barras laterais
- [ ] Página de filtro: diagramar, estilizar
- [x] Página de filtro: retrabalhar tabela para possibilitar rolagem mais confortável
- [x] Página de filtro: estilizar botões de paginação
- [x] Página de detalhe: diagramar, estilizar
- [x] Inserir espaçamento nas páginas de filtro e detalhe
- [x] Favicon

**Comment by andrechalom** [comment]
- Página de detalhe: 
- [x] substituir zigzag; 
- [ ] posicionamento de quebra de linha
- [x] centralizar foto no zigzag

**Comment by andrechalom** [comment]
- [x] Substituir text area da bio de candidato

**Comment by andrechalom** [comment]
- [x] Justificar texto bio candidato
